import os

TEAMS_BOT_TOKEN = os.getenv("TEAMS_BOT_TOKEN")
GOOGLE_SHEET_ID = os.getenv("GOOGLE_SHEET_ID")
GOOGLE_SERVICE_ACCOUNT_FILE = os.getenv("GOOGLE_SERVICE_ACCOUNT_FILE")
TEAMS_WEBHOOK_URL = os.getenv("TEAMS_WEBHOOK_URL")
